/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TheBookRouteImport } from './routes/the-book'
import { Route as PublicServiceRouteImport } from './routes/public-service'
import { Route as MyStoryRouteImport } from './routes/my-story'
import { Route as MediaRouteImport } from './routes/media'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'

const TheBookRoute = TheBookRouteImport.update({
  id: '/the-book',
  path: '/the-book',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicServiceRoute = PublicServiceRouteImport.update({
  id: '/public-service',
  path: '/public-service',
  getParentRoute: () => rootRouteImport,
} as any)
const MyStoryRoute = MyStoryRouteImport.update({
  id: '/my-story',
  path: '/my-story',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/media': typeof MediaRoute
  '/my-story': typeof MyStoryRoute
  '/public-service': typeof PublicServiceRoute
  '/the-book': typeof TheBookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/media': typeof MediaRoute
  '/my-story': typeof MyStoryRoute
  '/public-service': typeof PublicServiceRoute
  '/the-book': typeof TheBookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/media': typeof MediaRoute
  '/my-story': typeof MyStoryRoute
  '/public-service': typeof PublicServiceRoute
  '/the-book': typeof TheBookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/contact'
    | '/media'
    | '/my-story'
    | '/public-service'
    | '/the-book'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/contact'
    | '/media'
    | '/my-story'
    | '/public-service'
    | '/the-book'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/contact'
    | '/media'
    | '/my-story'
    | '/public-service'
    | '/the-book'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  MediaRoute: typeof MediaRoute
  MyStoryRoute: typeof MyStoryRoute
  PublicServiceRoute: typeof PublicServiceRoute
  TheBookRoute: typeof TheBookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/the-book': {
      id: '/the-book'
      path: '/the-book'
      fullPath: '/the-book'
      preLoaderRoute: typeof TheBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-service': {
      id: '/public-service'
      path: '/public-service'
      fullPath: '/public-service'
      preLoaderRoute: typeof PublicServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-story': {
      id: '/my-story'
      path: '/my-story'
      fullPath: '/my-story'
      preLoaderRoute: typeof MyStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  MediaRoute: MediaRoute,
  MyStoryRoute: MyStoryRoute,
  PublicServiceRoute: PublicServiceRoute,
  TheBookRoute: TheBookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
